modLoader = "javafml"
loaderVersion = "[37,)"
license = "GNU GPL 3.0"
issueTrackerURL="https://github.com/BigVirusBoi/CortexMod/issues/"
[[mods]]
modId = "cortexmod"
version = "${file.jarVersion}"
displayName = "Cortex Mod"
authors = "BigVirusBoi"
description = '''
BigVirusBoi's test mod for Kody Simpson
'''

[[dependencies.cortexmod]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cortexmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,1.18)"
ordering = "NONE"
side = "BOTH"
